apiVersion: v1
kind: ConfigMap
metadata:
  name: finkixp-config
  namespace: finkixp-ns
data:
  POSTGRES_DB: finkiXp
  POSTGRES_USER: emt
  SPRING_DATASOURCE_URL: jdbc:postgresql://finkixp-db:5432/finkiXp
---
apiVersion: v1
kind: Secret
metadata:
  name: finkixp-secrets
  namespace: finkixp-ns
type: Opaque
data:
  # echo -n 'emt' | base64
  POSTGRES_PASSWORD: ZW10
  SPRING_DATASOURCE_PASSWORD: ZW10
